/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_szmedchat_myjni_JNIUtil */

#ifndef _Included_com_szmedchat_myjni_JNIUtil
#define _Included_com_szmedchat_myjni_JNIUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_szmedchat_myjni_JNIUtil
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_szmedchat_myjni_JNIUtil_test
  (JNIEnv *, jobject);

/*
 * Class:     com_szmedchat_myjni_JNIUtil
 * Method:    createHashMap
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/util/HashMap;
 */
JNIEXPORT jobject JNICALL Java_com_szmedchat_myjni_JNIUtil_createHashMap
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
